# microservicios/exercises-sessions-service/Dockerfile
# Usa una imagen base de Python ligera
FROM python:3.12-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo de requisitos e instala las dependencias
RUN pip install poetry==1.8.2

# Copia el código de la aplicación
COPY pyproject.toml poetry.lock ./

RUN poetry install --no-root --no-dev --only main --sync

COPY ./app /app/app

# Expone el puerto en el que la aplicación FastAPI escuchará
EXPOSE 8001

# Comando para ejecutar la aplicación Uvicorn
# --host 0.0.0.0 es crucial para que sea accesible desde fuera del contenedor
CMD ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]