# plataforma-entrenamiento-deportivo/docker-compose/docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:16-alpine # Usamos la versión 16 de PostgreSQL, ligera con Alpine
    restart: always
    environment:
      POSTGRES_DB: auth_db # Nombre de la base de datos para el servicio de auth
      POSTGRES_USER: user # Usuario de la base de datos
      POSTGRES_PASSWORD: password # Contraseña del usuario
    ports:
      - "5432:5432" # Mapea el puerto del contenedor al host
    volumes:
      - db_data:/var/lib/postgresql/data # Persistencia de datos

volumes:
  db_data: # Define el volumen para la persistencia